### ISSUE TITLE
Force 20 FPS doesn't work If "Wait for vertical sync" is enabled. (At least in the HL25 version)

### ISSUE THREAD

**Issue by danylopez123** [ScriptedSnark/GSChaos#7]
I've saw an update that the "High" effect got fixed for the HL25 version by making it disable the shaders when it's activated.

You should also do a similar thing with the "Force 20 FPS" effect, seems that it only works if "Wait for vertical sync" is disabled, at least in the HL25 version, haven't tested this in the other versions yet.

**Comment by ScriptedSnark** [comment]
I wondered why 20 FPS thing doesn't work for some players. Thanks, will see what I can do.

**Comment by danylopez123** [comment]
No problem!
